#!/usr/bin/env python3
"""Generate browser catalog and readable design reference from canonical JSON."""
import argparse
import json
from html import escape
from pathlib import Path
from study_catalog import CATALOG, ROOT


def outputs():
    js = '// Generated by scripts/build_catalog.py; edit catalog/study-designs.json.\nexport const catalog = ' + json.dumps(CATALOG, ensure_ascii=False, indent=2) + ';\n'
    lines = ['# Choosing a study design', '',
             'Choose a research area, describe the goal, then compare suitable designs. Areas',
             'change examples and context; they do not determine or restrict the method.',
             'These are starting patterns, not a validated decision algorithm or an exhaustive taxonomy.', '',
             'The catalog was informed by the sources below. Reporting standards help document',
             'work; they cannot establish a valid design, sample size, approval or conclusion.', '',
             '## Research areas', '']
    for key, area in CATALOG['domains'].items():
        if key != 'undecided':
            lines += [f"### {area['label']}", '', ', '.join(area['subareas'].values()) + '.', '', area['context'], '']
    for goal, info in CATALOG['goals'].items():
        if goal == 'undecided':
            continue
        lines += ['## ' + info['label'], '', info['help'], '']
        for key, pattern in CATALOG['patterns'].items():
            if pattern['goal'] != goal:
                continue
            lines += ['### ' + pattern['label'], '', '**Use when:** ' + pattern['fit'], '',
                      '**Requires:** ' + pattern['needs'], '', '**Watch for:** ' + pattern['avoid'], '',
                      '**Example question:** ' + pattern['question'], '', '**Work sequence:**', '']
            lines += [f'{i}. {step}.' for i, step in enumerate(pattern['steps'], 1)]
            lines += ['', '**Analysis:** ' + pattern['analysis'], '', '**Decisions to record:**', '']
            lines += [f'- {label}: {hint}' for _, label, hint in pattern['fields']]
            lines += ['', f'CLI: `python research.py designs --pattern {key}`', '']
    lines += ['## Sources and scope', '',
              'Catalog guidance is an implementation choice; these sources have not evaluated',
              'the selector. Use relevant domain and methodological expertise for the actual study.', '']
    lines += [f"- [{s['label']}]({s['url']})" for s in CATALOG['sources'].values()]
    lines += ['', '[Implementation plan](study-design-plan.md) · [Methodology](methodology.md)', '']
    return {ROOT / 'site/catalog.mjs': js, ROOT / 'docs/study-designs.md': '\n'.join(lines), **public_pages()}


def public_pages():
    def page(title, intro, content):
        return ('<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
                '<title>'+escape(title)+' — Open Research</title><link rel="stylesheet" href="style.css?v=designs-2"></head><body>'
                '<a class="skip" href="#content">Skip to content</a><header class="site-header"><a class="brand" href="./"><span class="mark" aria-hidden="true">or.</span>Open Research</a>'
                '<nav aria-label="Main"><a href="./">Study editor</a><a href="guide.html">Start here</a><a href="paths.html">Guide paths</a><a href="designs.html">Choose a design</a><a href="examples.html">Examples</a><a href="tools.html">Tools &amp; skills</a><a href="about.html">About</a></nav></header>'
                '<main class="guide-page" id="content"><div class="guide-hero"><p class="eyebrow">AREA → GOAL → DESIGN → EVIDENCE</p><h1>'+escape(title)+'</h1><p class="lede">'+escape(intro)+'</p></div>'+content+'</main>'
                '<footer><span>Open Research · MIT licensed · Explain the choice; inspect the evidence.</span><a href="about.html#feedback">Report a problem →</a></footer></body></html>')
    areas='<section><h2>First, locate your research area</h2><div class="skill-recipes">'
    for key,a in CATALOG['domains'].items():
        if key=='undecided':continue
        areas+='<article><h3>'+escape(a['label'])+'</h3><p>'+escape(' · '.join(a['subareas'].values()))+'</p><p>'+escape(a['context'])+'</p></article>'
    areas+='</div><p>The area changes context, not the validity of a design. A medical device may need engineering bench tests, a diagnostic study and a user study for different claims.</p></section>'
    contents='<p><a class="guide-link" href="./?stage=plan">Use the guided selector in Plan →</a></p>'+areas+'<section><h2>Then, match the goal to the evidence you need</h2><p>Choose a situation below. Open its details to see prerequisites and the work sequence. Choosing “Use this design” carries the pattern to your current editor draft; existing notes stay intact.</p></section>'
    for goal,g in CATALOG['goals'].items():
        if goal=='undecided':continue
        contents+='<section id="goal-'+goal+'"><h2>'+escape(g['label'])+'</h2><p>'+escape(g['help'])+'</p>'
        for key,p in CATALOG['patterns'].items():
            if p['goal']!=goal:continue
            contents+='<article class="design-reference" id="'+key+'"><h3>'+escape(p['label'])+'</h3><p>'+escape(p['fit'])+'</p><details><summary>Required evidence, decisions and analysis</summary><p><strong>Requires:</strong> '+escape(p['needs'])+'</p><p><strong>Reconsider when:</strong> '+escape(p['avoid'])+'</p><p><strong>Illustrative question:</strong> '+escape(p['question'])+'</p><ol>'+''.join('<li>'+escape(s)+'</li>' for s in p['steps'])+'</ol><p><strong>Analysis:</strong> '+escape(p['analysis'])+'</p><ul>'+''.join('<li><strong>'+escape(label)+':</strong> '+escape(hint)+'</li>' for _,label,hint in p['fields'])+'</ul></details><p><a href="./?design='+key+'">Use this design in Plan →</a></p></article>'
        contents+='</section>'
    contents+='<section><h2>Basis and scope</h2><p>These 20 starting patterns are practical guidance, not a complete taxonomy or an automatic study-design decision. They are informed by the sources below; the sources have not validated this selector. Reporting checklists do not replace study design or scientific review.</p><ul>'+''.join('<li><a href="'+escape(s['url'],quote=True)+'">'+escape(s['label'])+'</a></li>' for s in CATALOG['sources'].values())+'</ul><p><a href="https://github.com/Chandrashekhar-Hegde/open-research/blob/main/docs/study-design-plan.md">Read the implementation plan →</a></p></section>'
    library='<p>Opening an example replaces the editor draft only after confirmation if it contains work. Save editable JSON first. A plan with no results is useful for learning the procedure, but is not a completed study.</p><div class="skill-recipes">'
    for key,e in CATALOG.get('examples',{}).items():
        library+='<article id="'+key+'"><p class="example-kind">'+escape(e['kind'])+'</p><h2>'+escape(e['label'])+'</h2><p>'+escape(e['description'])+'</p><p>'+escape(CATALOG['domains'][e['domain']]['label'])+' · '+escape(', '.join(CATALOG['patterns'][p]['label'] for p in e['patterns']))+'</p><pre tabindex="0">'+escape(e['command'])+'</pre><p><a href="./?example='+key+'">Open in editor →</a></p><p><a href="'+escape(e['guide'],quote=True)+'">Inputs, procedure and limits →</a></p></article>'
    library+='</div><p>From a local checkout, use <code>python</code> or <code>python3</code> as appropriate. Commands run locally; this static website does not execute Python or collect observations.</p>'
    from guide_paths import guide_outputs
    return {**guide_outputs(page), ROOT/'site/designs.html':page('Choose a design with a reason.','Start with your field and what you want to find out. You do not need to know a design name.',contents),
            ROOT/'site/examples.html':page('Follow the question through the work.','Real observations, computed teaching examples and honest plans with no invented results.',library)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    for path, body in outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding='utf-8') != body:
                parser.exit(1, f'Stale generated file: {path.name}; run python scripts/build_catalog.py\n')
        else:
            path.write_text(body, encoding='utf-8', newline='\n')
    print('PASS: browser catalog and design reference match canonical data.')


if __name__ == '__main__':
    main()
